service: my-money-bot

frameworkVersion: '3.33.0'

provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter*
      Resource: "arn:aws:ssm:us-east-1:646513389531:parameter/*"

functions:
  createFinancialProduct:
    handler: dist/main/handlers/api/index.createFinancialProduct
    events:
      - httpApi: 'POST /financial-products'

plugins:
  - serverless-offline
  - serverless-newrelic-lambda-layers