service: my-money-bot

frameworkVersion: '2.72.3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  getStockPrice:
    handler: dist/main/handlers/api/index.getStockPrice
    events:
      - httpApi: 'GET /stocks/{codeName}'
  myMoneyBotSkill:
    handler: dist/main/handlers/alexa/index.handlers
    events:
      - alexaSkill: amzn1.ask.skill.ab077192-4e04-40db-a522-ba73adbe06c9

plugins:
  - serverless-offline
