service: my-money-bot

frameworkVersion: '2.72.3'

provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter*
      Resource: "arn:aws:ssm:us-east-1:646513389531:parameter/*"
  environment:
    ALPHA_VANTAGE_API_URL: ${ssm:/ALPHA_VANTAGE_API_URL}
    ALPHA_VANTAGE_API_SECRET: ${ssm:/ALPHA_VANTAGE_API_SECRET}

functions:
  getStockPrice:
    handler: dist/main/handlers/api/index.getStockPrice
    events:
      - httpApi: 'GET /stocks/{codeName}'
  getStockName:
    handler: dist/main/handlers/api/index.getStockName
    events:
      - httpApi: 'GET /stocks/retrieve-name'
  myMoneyBotSkill:
    handler: dist/main/handlers/alexa/index.handlers
    events:
      - alexaSkill: amzn1.ask.skill.ab077192-4e04-40db-a522-ba73adbe06c9

plugins:
  - serverless-offline

custom:
  newRelic:
    accountId: ${ssm:/ENV_NEW_RELIC_ACCOUNT_ID}
    apiKey: ${ssm:/ENV_NEW_RELIC_API_KEY}
    enableExtension: true